### ISSUE TITLE
bat-scan needs configuration file

### ISSUE THREAD

**Issue by maxi1192** [armijnhemel/binaryanalysis#2]
Hi, 

when I run `bat-scan -b test.bin` I get the following error message

> usage: bat-scan [options]
> bat-scan: error: Need configuration file

what is the root cause for that?

**Comment by armijnhemel** [comment]
You will need to supply a configuration file. There is a sample file included in Git. You might want to grab the one from master, as I made a mistake in the default one from BAT 32 (oops).
