### ISSUE TITLE
Stops unpacking after searchUnpackYaffs2

### ISSUE THREAD

**Issue by maxi1192** [armijnhemel/binaryanalysis#3]
This is the output when I try to extract the firmware DVRF_v03.bin.
It works until it finishes yaffs2 unpacking. I guess after that exe unpack starts, right? what goes wrong? are there any debug info, because multiprocess totally masks error messages?

DVRF_v03.bin -o wasd
COPYING BEGIN 2016-11-30T20:22:22.677171
COPYING END 2016-11-30T20:22:22.982368
PRERUN UNPACK BEGIN 2016-11-30T20:22:26.223154
bat.prerun verifyELF /vagrant/tmp/unpack/tmpSMyDEz/data/DVRF_v03.bin 2016-11-30T20:22:26.460714
bat.prerun searchXML /vagrant/tmp/unpack/tmpSMyDEz/data/DVRF_v03.bin 2016-11-30T20:22:26.463020
bat.prerun verifyRSACertificate /vagrant/tmp/unpack/tmpSMyDEz/data/DVRF_v03.bin 2016-11-30T20:22:26.465210
bat.prerun verifyTZ /vagrant/tmp/unpack/tmpSMyDEz/data/DVRF_v03.bin 2016-11-30T20:22:26.465367
bat.prerun verifyChromePak /vagrant/tmp/unpack/tmpSMyDEz/data/DVRF_v03.bin 2016-11-30T20:22:26.468490
bat.prerun verifyVimSwap /vagrant/tmp/unpack/tmpSMyDEz/data/DVRF_v03.bin 2016-11-30T20:22:26.468603
bat.prerun verifyAndroidXML /vagrant/tmp/unpack/tmpSMyDEz/data/DVRF_v03.bin 2016-11-30T20:22:26.468688
bat.prerun verifyIco /vagrant/tmp/unpack/tmpSMyDEz/data/DVRF_v03.bin 2016-11-30T20:22:26.468782
bat.prerun verifyMessageCatalog /vagrant/tmp/unpack/tmpSMyDEz/data/DVRF_v03.bin 2016-11-30T20:22:26.468909
bat.prerun verifyCertificate /vagrant/tmp/unpack/tmpSMyDEz/data/DVRF_v03.bin 2016-11-30T20:22:26.469004
bat.prerun verifyAndroidResource /vagrant/tmp/unpack/tmpSMyDEz/data/DVRF_v03.bin 2016-11-30T20:22:26.469154
bat.prerun verifyTerminfo /vagrant/tmp/unpack/tmpSMyDEz/data/DVRF_v03.bin 2016-11-30T20:22:26.469247
bat.fwunpack searchUnpackByteSwap /vagrant/tmp/unpack/tmpSMyDEz/data/DVRF_v03.bin 2016-11-30T20:22:26.471940
bat.fwunpack searchUnpackAndroidSparseDataImage /vagrant/tmp/unpack/tmpSMyDEz/data/DVRF_v03.bin 2016-11-30T20:22:26.580553
bat.fwunpack searchUnpackExt2fs /vagrant/tmp/unpack/tmpSMyDEz/data/DVRF_v03.bin 2016-11-30T20:22:26.580788
bat.fwunpack searchUnpackYaffs2 /vagrant/tmp/unpack/tmpSMyDEz/data/DVRF_v03.bin 2016-11-30T20:22:26.604661
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bat/bruteforcescan.py", line 650, in scan
    scanres = locals()["bat_%s" % method](filetoscan, tempdir, blacklist, offsets, newenv, debug=debug)
  File "/usr/local/lib/python2.7/dist-packages/bat/fwunpack.py", line 1902, in searchUnpackYaffs2
    yaffsres = unpackYaffs(filename, offset, tmpdir)
  File "/usr/local/lib/python2.7/dist-packages/bat/fwunpack.py", line 1929, in unpackYaffs
    p = subprocess.Popen(['bat-unyaffs', '-b', filename, '-d', tmpdir, '-j', '-n', '%d' % offset], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by armijnhemel** [comment]
On 30/11/16 21:25, maxi1192 wrote:
> This is the output when I try to extract the firmware DVRF_v03.bin.
> It works until it finishes yaffs2 unpacking. I guess after that exe
> unpack starts, right? what goes wrong? are there any debug info,
> because multiprocess totally masks error messages?

It complains it cannot find "bat-unyaffs". This is part of
"bat-extratools". Have you installed "bat-extratools" as a package on
your system? Having it installed as a package is quite important,
because BAT looks for this program in the standard PATH.

armijn


-- 
Armijn Hemel, MSc
Tjaldur Software Governance Solutions

**Comment by maxi1192** [comment]
Thank you for your fast Support
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 30.11.16, 23:44, armijnhemel <notifications@github.com> schrieb:

  
    On 30/11/16 21:25, maxi1192 wrote:
    > This is the output when I try to extract the firmware DVRF_v03.bin.
    > It works until it finishes yaffs2 unpacking. I guess after that exe
    > unpack starts, right? what goes wrong? are there any debug info,
    > because multiprocess totally masks error messages?
    
    It complains it cannot find "bat-unyaffs". This is part of
    "bat-extratools". Have you installed "bat-extratools" as a package on
    your system? Having it installed as a package is quite important,
    because BAT looks for this program in the standard PATH.
    
    armijn
    
    
    --
    Armijn Hemel, MSc
    Tjaldur Software Governance Solutions

**Comment by maxi1192** [comment]
Actually now I installed bat-extractools and bat-extratools-java, but this does not change the error message. What am I doing wrong? The procedure to install bat-extratools is just running "make" in sudo mode, right? Is it important to install bat before bet-extratools or vice versa?

**Comment by armijnhemel** [comment]
If the error is the same, then it means that your PATH is set incorrectly.
