### ISSUE TITLE
build error on the BAT36

### ISSUE THREAD

**Issue by haksungjang** [armijnhemel/binaryanalysis#4]
I tried to build bat 36.0 to apply the fixed file but the following error occurred. :

$ git clone https://github.com/armijnhemel/binaryanalysis.git
Cloning into 'binaryanalysis'...
remote: Counting objects: 26603, done.
remote: Compressing objects: 100% (156/156), done.
remote: Total 26603 (delta 101), reused 0 (delta 0), pack-reused 26447
Receiving objects: 100% (26603/26603), 4.07 MiB | 728.00 KiB/s, done.
Resolving deltas: 100% (15107/15107), done.
Checking connectivity... done.
$ cd binaryanalysis/src
binaryanalysis/src$ debuild -uc -us
dpkg-buildpackage -rfakeroot -D -us -uc
dpkg-buildpackage: export CFLAGS from dpkg-buildflags (origin: vendor): -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security
dpkg-buildpackage: export CPPFLAGS from dpkg-buildflags (origin: vendor): -D_FORTIFY_SOURCE=2
dpkg-buildpackage: export CXXFLAGS from dpkg-buildflags (origin: vendor): -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security
dpkg-buildpackage: export FFLAGS from dpkg-buildflags (origin: vendor): -g -O2
dpkg-buildpackage: export LDFLAGS from dpkg-buildflags (origin: vendor): -Wl,-Bsymbolic-functions -Wl,-z,relro
dpkg-buildpackage: source package bat
dpkg-buildpackage: source version 36.0
dpkg-buildpackage: source changed by Armijn Hemel <armijn@binaryanalysis.org>
dpkg-source --before-build src
dpkg-buildpackage: host architecture amd64
fakeroot debian/rules clean
dh clean
dh_testdir
dh_auto_clean
running clean
'build/lib.linux-x86_64-2.7' does not exist – can't clean it
'build/bdist.linux-x86_64' does not exist – can't clean it
'build/scripts-2.7' does not exist – can't clean it
dh_clean
dpkg-source -b src
dpkg-source: warning: no source format specified in debian/source/format, see dpkg-source(1)
dpkg-source: warning: source directory 'src' is not <sourcepackage>-<upstreamversion> 'bat-36.0'
dpkg-source: info: using source format `1.0'
dpkg-source: info: building bat in bat_36.0.tar.gz
dpkg-source: info: building bat in bat_36.0.dsc
debian/rules build
dh build
dh_testdir
dh_auto_configure
dh_auto_build
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/bat
copying bat/bruteforcescan.py -> build/lib.linux-x86_64-2.7/bat
copying bat/unpackrpm.py -> build/lib.linux-x86_64-2.7/bat
copying bat/fwunpack.py -> build/lib.linux-x86_64-2.7/bat
copying bat/busyboxversion.py -> build/lib.linux-x86_64-2.7/bat
copying bat/file2package.py -> build/lib.linux-x86_64-2.7/bat
copying bat/findduplicates.py -> build/lib.linux-x86_64-2.7/bat
copying bat/prerun.py -> build/lib.linux-x86_64-2.7/bat
copying bat/fixduplicates.py -> build/lib.linux-x86_64-2.7/bat
copying bat/licenseversion.py -> build/lib.linux-x86_64-2.7/bat
copying bat/jffs2.py -> build/lib.linux-x86_64-2.7/bat
copying bat/ext2.py -> build/lib.linux-x86_64-2.7/bat
copying bat/reportcopyright.py -> build/lib.linux-x86_64-2.7/bat
copying bat/extractor.py -> build/lib.linux-x86_64-2.7/bat
copying bat/piecharts.py -> build/lib.linux-x86_64-2.7/bat
copying bat/generatejson.py -> build/lib.linux-x86_64-2.7/bat
copying bat/fsmagic.py -> build/lib.linux-x86_64-2.7/bat
copying bat/busybox.py -> build/lib.linux-x86_64-2.7/bat
copying bat/identifier.py -> build/lib.linux-x86_64-2.7/bat
copying bat/kernelanalysis.py -> build/lib.linux-x86_64-2.7/bat
copying bat/generatehexdump.py -> build/lib.linux-x86_64-2.7/bat
copying bat/renamefiles.py -> build/lib.linux-x86_64-2.7/bat
copying bat/kernelsymbols.py -> build/lib.linux-x86_64-2.7/bat
copying bat/generatereports.py -> build/lib.linux-x86_64-2.7/bat
copying bat/fssearch.py -> build/lib.linux-x86_64-2.7/bat
copying bat/_init_.py -> build/lib.linux-x86_64-2.7/bat
copying bat/elfcheck.py -> build/lib.linux-x86_64-2.7/bat
copying bat/security.py -> build/lib.linux-x86_64-2.7/bat
copying bat/guireport.py -> build/lib.linux-x86_64-2.7/bat
copying bat/javacheck.py -> build/lib.linux-x86_64-2.7/bat
copying bat/findlibs.py -> build/lib.linux-x86_64-2.7/bat
copying bat/checks.py -> build/lib.linux-x86_64-2.7/bat
copying bat/images.py -> build/lib.linux-x86_64-2.7/bat
copying bat/prunefiles.py -> build/lib.linux-x86_64-2.7/bat
copying bat/batxor.py -> build/lib.linux-x86_64-2.7/bat
copying bat/derivekernelconfig.py -> build/lib.linux-x86_64-2.7/bat
copying bat/generateimages.py -> build/lib.linux-x86_64-2.7/bat
copying bat/interfaces.py -> build/lib.linux-x86_64-2.7/bat
running build_scripts
creating build/scripts-2.7
error: maintenance/batconfigcheck.py: No such file or directory
dh_auto_build: python setup.py build --force returned exit code 1
make: *** [build] Error 1
dpkg-buildpackage: error: debian/rules build gave error exit status 2
debuild: fatal error at line 1350:
dpkg-buildpackage -rfakeroot -D -us -uc failed

**Comment by armijnhemel** [comment]
>   error: maintenance/batconfigcheck.py: No such file or directory
>

I forgot to remove batconfigcheck.py in setup.py. This has been fixed.


armijn


-- 
Armijn Hemel, MSc
Tjaldur Software Governance Solutions
