### ISSUE TITLE
module' object has no attribute 'open'

### ISSUE THREAD

**Issue by cyphunk** [armijnhemel/binaryanalysis#7]
There is a note in the code suggesting their are many incompatible magic module versions. I could not find documentation anywhere in the package or project website about requirements, or which version of this module may be required. Could someone suggest which version works?

https://github.com/armijnhemel/binaryanalysis/blob/791476166f854ba3daf6ecf327640485a4514535/src/bat/bruteforcescan.py#L54

**Comment by cyphunk** [comment]
So far I seem to get things moving along when using the python code found here: https://github.com/threatstack/libmagic

**Comment by armijnhemel** [comment]
The recommended one is the one that is standard on Fedora and Ubuntu

On my Fedora system:

$ rpm -qi python-magic
Name        : python-magic
Version     : 5.30
Release     : 11.fc26
Architecture: noarch
Install Date: Wed 13 Sep 2017 12:26:45 PM CEST
Group       : Development/Libraries
Size        : 21349
License     : BSD
Signature   : RSA/SHA256, Fri 08 Sep 2017 06:20:19 PM CEST, Key ID 812a6b4b64dab85d
Source RPM  : file-5.30-11.fc26.src.rpm
Build Date  : Fri 08 Sep 2017 05:58:39 PM CEST
Build Host  : buildvm-17.phx2.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://www.darwinsys.com/file/
Summary     : Python 2 bindings for the libmagic API
Description :
This package contains the Python 2 bindings to allow access to the
libmagic API. The libmagic library is also used by the familiar
file(1) command.
